### ISSUE TITLE
Support Export and Import jobs as files 

### ISSUE THREAD

**Issue by ernestoongaro** [data-mie/dbt-cloud-cli#12]
Will this allow to export jobs to file and import them again? Getting users moving from single-tenant to multi-tenant dbt cloud (and vice versa) this would be 🤤

**Comment by stumelius** [comment]
@ernestoongaro That's an excellent suggestion! Do you have any suggestions for the serialization format? JSON or something else? The format should support moving other components, such as environments, too.

**Comment by ernestoongaro** [comment]
Awesome @stumelius ! My preference would be json, seems to be popular to use tools like jq to do some light manipulation of the file from the command line
