### ISSUE TITLE
issue installing latest version  No module named 'dbt_cloud.command'

### ISSUE THREAD

**Issue by ernestoongaro** [data-mie/dbt-cloud-cli#37]
See below - installed 0.3, worked fine, then 0.5, not fine!

0.30 - works fine:

(env) ernesto@Ernesto-Ongaro dbt_cloud_api % python3 -m pip install dbt-cloud-cli==0.3.0
Collecting dbt-cloud-cli==0.3.0
  Using cached dbt_cloud_cli-0.3.0-py3-none-any.whl (15 kB)
Requirement already satisfied: requests in ./env/lib/python3.9/site-packages (from dbt-cloud-cli==0.3.0) (2.27.1)
Requirement already satisfied: click in ./env/lib/python3.9/site-packages (from dbt-cloud-cli==0.3.0) (8.0.3)
Requirement already satisfied: mergedeep in ./env/lib/python3.9/site-packages (from dbt-cloud-cli==0.3.0) (1.3.4)
Requirement already satisfied: pydantic in ./env/lib/python3.9/site-packages (from dbt-cloud-cli==0.3.0) (1.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./env/lib/python3.9/site-packages (from pydantic->dbt-cloud-cli==0.3.0) (4.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli==0.3.0) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli==0.3.0) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli==0.3.0) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli==0.3.0) (2.0.10)
Installing collected packages: dbt-cloud-cli
  Attempting uninstall: dbt-cloud-cli
    Found existing installation: dbt-cloud-cli 0.4.0
    Uninstalling dbt-cloud-cli-0.4.0:
      Successfully uninstalled dbt-cloud-cli-0.4.0
Successfully installed dbt-cloud-cli-0.3.0
(env) ernesto@Ernesto-Ongaro dbt_cloud_api % dbt-cloud
Usage: dbt-cloud [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  job
  run

Then 0.5.0:
(env) ernesto@Ernesto-Ongaro dbt_cloud_api % python3 -m pip install dbt-cloud-cli --upgrade
Requirement already satisfied: dbt-cloud-cli in ./env/lib/python3.9/site-packages (0.3.0)
Collecting dbt-cloud-cli
  Using cached dbt_cloud_cli-0.5.0-py3-none-any.whl (13 kB)
Requirement already satisfied: mergedeep in ./env/lib/python3.9/site-packages (from dbt-cloud-cli) (1.3.4)
Requirement already satisfied: requests in ./env/lib/python3.9/site-packages (from dbt-cloud-cli) (2.27.1)
Requirement already satisfied: click in ./env/lib/python3.9/site-packages (from dbt-cloud-cli) (8.0.3)
Requirement already satisfied: pydantic in ./env/lib/python3.9/site-packages (from dbt-cloud-cli) (1.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./env/lib/python3.9/site-packages (from pydantic->dbt-cloud-cli) (4.0.1)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./env/lib/python3.9/site-packages (from requests->dbt-cloud-cli) (2.0.10)
Installing collected packages: dbt-cloud-cli
  Attempting uninstall: dbt-cloud-cli
    Found existing installation: dbt-cloud-cli 0.3.0
    Uninstalling dbt-cloud-cli-0.3.0:
      Successfully uninstalled dbt-cloud-cli-0.3.0
Successfully installed dbt-cloud-cli-0.5.0
(env) ernesto@Ernesto-Ongaro dbt_cloud_api % dbt-cloud
Traceback (most recent call last):
  File "/Users/ernesto/Dev/dbt_cloud_api/env/bin/dbt-cloud", line 5, in <module>
    from dbt_cloud.cli import dbt_cloud
  File "/Users/ernesto/Dev/dbt_cloud_api/env/lib/python3.9/site-packages/dbt_cloud/__init__.py", line 1, in <module>
    from .command import DbtCloudRunStatus
ModuleNotFoundError: No module named 'dbt_cloud.command'
(env) ernesto@Ernesto-Ongaro dbt_cloud_api %

**Comment by ernestoongaro** [comment]
@saraleon1

**Comment by stumelius** [comment]
Oh crap, how did I miss that! Thanks for reporting this @ernestoongaro. I'm in the middle of something atm but I'll get back to this later today.

**Comment by stumelius** [comment]
@ernestoongaro I had hard-coded the `packages` variable in `setup.py` which resulted in the `dbt_cloud.command` subpackage being omitted from the distribution I published to PyPI 🤦 It's fixed now and I've released version 0.5.1. Let me know if you encounter any further issues.

**Comment by ernestoongaro** [comment]
Thank you! Confirmed upgrade to 0.5.1 fixed it 🎉
