### ISSUE TITLE
support single tenant dbt cloud deployments

### ISSUE THREAD

**Issue by ernestoongaro** [data-mie/dbt-cloud-cli#38]
dbt Cloud can be deployed either multi-tenant (i.e url is cloud.getdbt.com) or single-tenant, where a customer chooses their own url (like cloud.customer.getdbt.com) a bit more about it [here](https://docs.getdbt.com/docs/dbt-cloud/deployments/single-tenant-deployment)

**Comment by stumelius** [comment]
Implemented in #39
