### ISSUE TITLE
dbt-cloud run cancel-all

### ISSUE THREAD

**Issue by jeremyyeo** [data-mie/dbt-cloud-cli#46]
Add the ability to cancel all existing runs similar to `job delete-all`. 

Should build on top existing https://github.com/data-mie/dbt-cloud-cli#dbt-cloud-run-cancel

**Comment by stumelius** [comment]
Thanks for the suggestion @jeremyyeo ! As you said, this needs to be built on top of `dbt-cloud run-cancel`. It should also leverage `dbt-cloud run list --status Running` + `dbt-cloud run list --status Queued`. Do you want to have a crack at this? You can use [dbt-cloud job delete-all](https://github.com/data-mie/dbt-cloud-cli/blob/435e14c7237daecb48dadfe564eada43452dbc01/dbt_cloud/cli.py#L164) as reference.
