### ISSUE TITLE
Allow `dbt-cloud metadata query` to accept the query as stdin/inline string

### ISSUE THREAD

**Issue by b-per** [data-mie/dbt-cloud-cli#55]
First of all, thanks a lot for the work here, this is amazing.

I have been looking at `dbt-cloud metadata query` and was expecting to be able to run a query like:
```
dbt-cloud metadata query '{
  model(jobId: xxxxx, uniqueId:"xxxx") {
    name
    uniqueId
    type
    jobId
  }
}'
```
but it returned `Error: Got unexpected extra argument ({ ........})`

I was able to run the query by saving it in a file and using `-f file_name` though.

Is there a way to run a metadata query inline or is the only way with `-f` ? My use case was to get all the jobs with `dbt-cloud job list` and pipe this list with xargs to run a metadata query for each job.

If this is not possible today, would you be OK with a contribution to make it possible?

**Comment by stumelius** [comment]
@b-per The `-f` argument takes a piped input by default, i.e. this should work:

```bash
echo '{
  model(jobId: xxxxx, uniqueId:"xxxx") {
    name
    uniqueId
    type
    jobId
  }
}' | dbt-cloud metadata query
```

Let me know if this fits your use case :)

**Comment by b-per** [comment]
Thanks for the answer, it worked! Not sure if is worth adding an example without the `-f` in the README. (I can do it if you agree that another example could help).

For my use case (listing all models run by all jobs), the following pipes of commands gave me the output I was after:
```shell
dbt-cloud job list | jq '.data[].id' | xargs -I % sh -c 'echo "query {
  models(jobId: %){
    runId
    uniqueId
  }
}" | dbt-cloud metadata query'
```
