### ISSUE TITLE
How to set up and use

### ISSUE THREAD

**Issue by garfieldthesam** [data-mie/dbt-cloud-cli#69]
It's unclear from the `README` and other artifacts in the repo (or from a google search) how to actually set up and use this package. In my case I'm working in MacOS Ventura. 

I have used the command `python3 -m pip install dbt-cloud-cli` to install the package via terminal (running `zsh`) as suggested in [the blog post](https://docs.getdbt.com/blog/making-dbt-cloud-api-calls-using-dbt-cloud-cli. However, I am not able to invoke `dbt-cloud` from the CLI as the blog post seems to suggest.

**Comment by stumelius** [comment]
The CLI is installed as a [console_scripts entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) when you run `python3 -m pip install dbt-cloud-cli`. It's difficult to say why your shell doesn't find the entrypoint. Have you tried installing it in a Python virtual environment?

**Comment by garfieldthesam** [comment]
Just installed using a `venv` and am still unable to invoke from the CLI

**Comment by garfieldthesam** [comment]
BUT I just got it to work by doing the following after looking up common issues with console_scripts entry points:

1. Ran `python3 -m pip install dbt-cloud-cli --force`
2. Modified my `.zshrc` to include `export PATH=~/Library/Python/3.9/bin:$PATH`

Thanks! Looking forward to using this package!

**Comment by stumelius** [comment]
@garfieldthesam I'm glad you managed to fix it :) And thanks for sharing the solution!
