### ISSUE TITLE
Unable to create a job using dbt-cloud job create command in command-line

### ISSUE THREAD

**Issue by YagnaSriramA** [data-mie/dbt-cloud-cli#73]
I am trying to create a job. But it is throwing an error with the execute steps parameter. 
The following is my command - 
**dbt-cloud job create --project-id 241666 --environment-id 188496 --name "NewJob" --execute-steps ["dbt run"]**

Following is the error that it is throwing:
**Error: Invalid value for '--execute-steps': [dbt run]** 

I was initially trying to create a job using the dbt API by sending a post request which was also not working. The response shows that various parameter values in the request body are not valid. It would be great if someone could help me with the API problem as well. We are trying to automatically create jobs on the go based on a few parameters but manually doing that using API itself is not working.

**Comment by stumelius** [comment]
@YagnaSriramA You need to wrap the --execute-steps argument in quotes so it is parsed as a string:

**Comment by YagnaSriramA** [comment]
thank you for the reply @stumelius. 

It did not work. It said - 

**1 validation error for DbtCloudJobCreateCommand 
execute_steps
  value is not a valid list (type=type_error.list)**

**Comment by stumelius** [comment]
@YagnaSriramA I can't reproduce the error with 

```
dbt-cloud job create --project-id 241666 --environment-id 188496 --name "NewJob" --execute-steps '["dbt run"]'
```

but with

```
dbt-cloud job create --project-id 241666 --environment-id 188496 --name "NewJob" --execute-steps '"dbt run"'
```

I can. Did you wrap the execute-steps list in quotes or did you strip away the list before wrapping the argument in quotes? i.e., use `'["dbt run"]'` instead of '"dbt run"'.

**Comment by stumelius** [comment]
Closing this after over 3 months of inactivity
