### ISSUE TITLE
Newly released Pydantic version has a breaking change in dbt-cloud-cli

### ISSUE THREAD

**Issue by runar-alvseike** [data-mie/dbt-cloud-cli#74]
Following the new version of Pydantic provides an breaking change in `dbt-cloud-cli`.

Running `dbt-cloud job <arguments>` provides the following traceback:
`pydantic.errors.PydanticUserError: The `field` and `config` parameters are not available in Pydantic V2, please use the `info` parameter instead.`

**Comment by wonkyto** [comment]
I also had this problem - it had worked a week earlier, but on a fresh `pip install dbt-cloud-cli` I came across this issue when pydantic 2.0.2 was installed automatically.

By first installing pydantic 1.10.9 before dbt-cloud-cli I was able to work around this issue

```
pip install pydantic==1.10.9
pip install dbt-cloud-cli
```

**Comment by stumelius** [comment]
Fixed in #75

**Comment by stumelius** [comment]
@runar-alvseike FYI https://github.com/data-mie/dbt-cloud-cli/releases/tag/0.7.6
